/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcompanhamentoRouteImport } from './routes/acompanhamento'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ConfirmarCorridaRouteImport } from './routes/confirmar-corrida'
import { Route as CorridasRouteImport } from './routes/corridas'
import { Route as HomeMotoristaRouteImport } from './routes/home-motorista'
import { Route as MeusChamadosRouteImport } from './routes/meus-chamados'
import { Route as OnboardingMotoristaRouteImport } from './routes/onboarding-motorista'
import { Route as PagamentoPixRouteImport } from './routes/pagamento-pix'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as PerfilMotoristaRouteImport } from './routes/perfil-motorista'
import { Route as ProcurandoMotoristaRouteImport } from './routes/procurando-motorista'
import { Route as ViagemCompartilhadaRouteImport } from './routes/viagem-compartilhada'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminCidadesRouteImport } from './routes/admin/cidades'
import { Route as AdminMotoristasRouteImport } from './routes/admin/motoristas'
import { Route as AdminSuporteRouteImport } from './routes/admin/suporte'
import { Route as AdminVeiculosRouteImport } from './routes/admin/veiculos'
import { Route as AuthCadastroRouteImport } from './routes/auth.cadastro'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthCompletarCadastroRouteImport } from './routes/auth.completar-cadastro'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthPerfilRouteImport } from './routes/auth.perfil'
import { Route as MotoristaMercadopagoCallbackRouteImport } from './routes/motorista.mercadopago-callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcompanhamentoRoute = AcompanhamentoRouteImport.update({
  id: '/acompanhamento',
  path: '/acompanhamento',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmarCorridaRoute = ConfirmarCorridaRouteImport.update({
  id: '/confirmar-corrida',
  path: '/confirmar-corrida',
  getParentRoute: () => rootRouteImport,
} as any)
const CorridasRoute = CorridasRouteImport.update({
  id: '/corridas',
  path: '/corridas',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeMotoristaRoute = HomeMotoristaRouteImport.update({
  id: '/home-motorista',
  path: '/home-motorista',
  getParentRoute: () => rootRouteImport,
} as any)
const MeusChamadosRoute = MeusChamadosRouteImport.update({
  id: '/meus-chamados',
  path: '/meus-chamados',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingMotoristaRoute = OnboardingMotoristaRouteImport.update({
  id: '/onboarding-motorista',
  path: '/onboarding-motorista',
  getParentRoute: () => rootRouteImport,
} as any)
const PagamentoPixRoute = PagamentoPixRouteImport.update({
  id: '/pagamento-pix',
  path: '/pagamento-pix',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilMotoristaRoute = PerfilMotoristaRouteImport.update({
  id: '/perfil-motorista',
  path: '/perfil-motorista',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcurandoMotoristaRoute = ProcurandoMotoristaRouteImport.update({
  id: '/procurando-motorista',
  path: '/procurando-motorista',
  getParentRoute: () => rootRouteImport,
} as any)
const ViagemCompartilhadaRoute = ViagemCompartilhadaRouteImport.update({
  id: '/viagem-compartilhada',
  path: '/viagem-compartilhada',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCidadesRoute = AdminCidadesRouteImport.update({
  id: '/admin/cidades',
  path: '/admin/cidades',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMotoristasRoute = AdminMotoristasRouteImport.update({
  id: '/admin/motoristas',
  path: '/admin/motoristas',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSuporteRoute = AdminSuporteRouteImport.update({
  id: '/admin/suporte',
  path: '/admin/suporte',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVeiculosRoute = AdminVeiculosRouteImport.update({
  id: '/admin/veiculos',
  path: '/admin/veiculos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCadastroRoute = AuthCadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCompletarCadastroRoute = AuthCompletarCadastroRouteImport.update({
  id: '/completar-cadastro',
  path: '/completar-cadastro',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPerfilRoute = AuthPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthRoute,
} as any)
const MotoristaMercadopagoCallbackRoute =
  MotoristaMercadopagoCallbackRouteImport.update({
    id: '/motorista/mercadopago-callback',
    path: '/motorista/mercadopago-callback',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acompanhamento': typeof AcompanhamentoRoute
  '/auth': typeof AuthRouteWithChildren
  '/confirmar-corrida': typeof ConfirmarCorridaRoute
  '/corridas': typeof CorridasRoute
  '/home-motorista': typeof HomeMotoristaRoute
  '/meus-chamados': typeof MeusChamadosRoute
  '/onboarding-motorista': typeof OnboardingMotoristaRoute
  '/pagamento-pix': typeof PagamentoPixRoute
  '/perfil': typeof PerfilRoute
  '/perfil-motorista': typeof PerfilMotoristaRoute
  '/procurando-motorista': typeof ProcurandoMotoristaRoute
  '/viagem-compartilhada': typeof ViagemCompartilhadaRoute
  '/admin/cidades': typeof AdminCidadesRoute
  '/admin/motoristas': typeof AdminMotoristasRoute
  '/admin/suporte': typeof AdminSuporteRoute
  '/admin/veiculos': typeof AdminVeiculosRoute
  '/auth/cadastro': typeof AuthCadastroRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/completar-cadastro': typeof AuthCompletarCadastroRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/perfil': typeof AuthPerfilRoute
  '/motorista/mercadopago-callback': typeof MotoristaMercadopagoCallbackRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acompanhamento': typeof AcompanhamentoRoute
  '/auth': typeof AuthRouteWithChildren
  '/confirmar-corrida': typeof ConfirmarCorridaRoute
  '/corridas': typeof CorridasRoute
  '/home-motorista': typeof HomeMotoristaRoute
  '/meus-chamados': typeof MeusChamadosRoute
  '/onboarding-motorista': typeof OnboardingMotoristaRoute
  '/pagamento-pix': typeof PagamentoPixRoute
  '/perfil': typeof PerfilRoute
  '/perfil-motorista': typeof PerfilMotoristaRoute
  '/procurando-motorista': typeof ProcurandoMotoristaRoute
  '/viagem-compartilhada': typeof ViagemCompartilhadaRoute
  '/admin/cidades': typeof AdminCidadesRoute
  '/admin/motoristas': typeof AdminMotoristasRoute
  '/admin/suporte': typeof AdminSuporteRoute
  '/admin/veiculos': typeof AdminVeiculosRoute
  '/auth/cadastro': typeof AuthCadastroRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/completar-cadastro': typeof AuthCompletarCadastroRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/perfil': typeof AuthPerfilRoute
  '/motorista/mercadopago-callback': typeof MotoristaMercadopagoCallbackRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acompanhamento': typeof AcompanhamentoRoute
  '/auth': typeof AuthRouteWithChildren
  '/confirmar-corrida': typeof ConfirmarCorridaRoute
  '/corridas': typeof CorridasRoute
  '/home-motorista': typeof HomeMotoristaRoute
  '/meus-chamados': typeof MeusChamadosRoute
  '/onboarding-motorista': typeof OnboardingMotoristaRoute
  '/pagamento-pix': typeof PagamentoPixRoute
  '/perfil': typeof PerfilRoute
  '/perfil-motorista': typeof PerfilMotoristaRoute
  '/procurando-motorista': typeof ProcurandoMotoristaRoute
  '/viagem-compartilhada': typeof ViagemCompartilhadaRoute
  '/admin/cidades': typeof AdminCidadesRoute
  '/admin/motoristas': typeof AdminMotoristasRoute
  '/admin/suporte': typeof AdminSuporteRoute
  '/admin/veiculos': typeof AdminVeiculosRoute
  '/auth/cadastro': typeof AuthCadastroRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/completar-cadastro': typeof AuthCompletarCadastroRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/perfil': typeof AuthPerfilRoute
  '/motorista/mercadopago-callback': typeof MotoristaMercadopagoCallbackRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acompanhamento'
    | '/auth'
    | '/confirmar-corrida'
    | '/corridas'
    | '/home-motorista'
    | '/meus-chamados'
    | '/onboarding-motorista'
    | '/pagamento-pix'
    | '/perfil'
    | '/perfil-motorista'
    | '/procurando-motorista'
    | '/viagem-compartilhada'
    | '/admin/cidades'
    | '/admin/motoristas'
    | '/admin/suporte'
    | '/admin/veiculos'
    | '/auth/cadastro'
    | '/auth/callback'
    | '/auth/completar-cadastro'
    | '/auth/login'
    | '/auth/perfil'
    | '/motorista/mercadopago-callback'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acompanhamento'
    | '/auth'
    | '/confirmar-corrida'
    | '/corridas'
    | '/home-motorista'
    | '/meus-chamados'
    | '/onboarding-motorista'
    | '/pagamento-pix'
    | '/perfil'
    | '/perfil-motorista'
    | '/procurando-motorista'
    | '/viagem-compartilhada'
    | '/admin/cidades'
    | '/admin/motoristas'
    | '/admin/suporte'
    | '/admin/veiculos'
    | '/auth/cadastro'
    | '/auth/callback'
    | '/auth/completar-cadastro'
    | '/auth/login'
    | '/auth/perfil'
    | '/motorista/mercadopago-callback'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/acompanhamento'
    | '/auth'
    | '/confirmar-corrida'
    | '/corridas'
    | '/home-motorista'
    | '/meus-chamados'
    | '/onboarding-motorista'
    | '/pagamento-pix'
    | '/perfil'
    | '/perfil-motorista'
    | '/procurando-motorista'
    | '/viagem-compartilhada'
    | '/admin/cidades'
    | '/admin/motoristas'
    | '/admin/suporte'
    | '/admin/veiculos'
    | '/auth/cadastro'
    | '/auth/callback'
    | '/auth/completar-cadastro'
    | '/auth/login'
    | '/auth/perfil'
    | '/motorista/mercadopago-callback'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcompanhamentoRoute: typeof AcompanhamentoRoute
  AuthRoute: typeof AuthRouteWithChildren
  ConfirmarCorridaRoute: typeof ConfirmarCorridaRoute
  CorridasRoute: typeof CorridasRoute
  HomeMotoristaRoute: typeof HomeMotoristaRoute
  MeusChamadosRoute: typeof MeusChamadosRoute
  OnboardingMotoristaRoute: typeof OnboardingMotoristaRoute
  PagamentoPixRoute: typeof PagamentoPixRoute
  PerfilRoute: typeof PerfilRoute
  PerfilMotoristaRoute: typeof PerfilMotoristaRoute
  ProcurandoMotoristaRoute: typeof ProcurandoMotoristaRoute
  ViagemCompartilhadaRoute: typeof ViagemCompartilhadaRoute
  AdminCidadesRoute: typeof AdminCidadesRoute
  AdminMotoristasRoute: typeof AdminMotoristasRoute
  AdminSuporteRoute: typeof AdminSuporteRoute
  AdminVeiculosRoute: typeof AdminVeiculosRoute
  MotoristaMercadopagoCallbackRoute: typeof MotoristaMercadopagoCallbackRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acompanhamento': {
      id: '/acompanhamento'
      path: '/acompanhamento'
      fullPath: '/acompanhamento'
      preLoaderRoute: typeof AcompanhamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmar-corrida': {
      id: '/confirmar-corrida'
      path: '/confirmar-corrida'
      fullPath: '/confirmar-corrida'
      preLoaderRoute: typeof ConfirmarCorridaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corridas': {
      id: '/corridas'
      path: '/corridas'
      fullPath: '/corridas'
      preLoaderRoute: typeof CorridasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home-motorista': {
      id: '/home-motorista'
      path: '/home-motorista'
      fullPath: '/home-motorista'
      preLoaderRoute: typeof HomeMotoristaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meus-chamados': {
      id: '/meus-chamados'
      path: '/meus-chamados'
      fullPath: '/meus-chamados'
      preLoaderRoute: typeof MeusChamadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding-motorista': {
      id: '/onboarding-motorista'
      path: '/onboarding-motorista'
      fullPath: '/onboarding-motorista'
      preLoaderRoute: typeof OnboardingMotoristaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagamento-pix': {
      id: '/pagamento-pix'
      path: '/pagamento-pix'
      fullPath: '/pagamento-pix'
      preLoaderRoute: typeof PagamentoPixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil-motorista': {
      id: '/perfil-motorista'
      path: '/perfil-motorista'
      fullPath: '/perfil-motorista'
      preLoaderRoute: typeof PerfilMotoristaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procurando-motorista': {
      id: '/procurando-motorista'
      path: '/procurando-motorista'
      fullPath: '/procurando-motorista'
      preLoaderRoute: typeof ProcurandoMotoristaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/viagem-compartilhada': {
      id: '/viagem-compartilhada'
      path: '/viagem-compartilhada'
      fullPath: '/viagem-compartilhada'
      preLoaderRoute: typeof ViagemCompartilhadaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/cidades': {
      id: '/admin/cidades'
      path: '/admin/cidades'
      fullPath: '/admin/cidades'
      preLoaderRoute: typeof AdminCidadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/motoristas': {
      id: '/admin/motoristas'
      path: '/admin/motoristas'
      fullPath: '/admin/motoristas'
      preLoaderRoute: typeof AdminMotoristasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/suporte': {
      id: '/admin/suporte'
      path: '/admin/suporte'
      fullPath: '/admin/suporte'
      preLoaderRoute: typeof AdminSuporteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/veiculos': {
      id: '/admin/veiculos'
      path: '/admin/veiculos'
      fullPath: '/admin/veiculos'
      preLoaderRoute: typeof AdminVeiculosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/cadastro': {
      id: '/auth/cadastro'
      path: '/cadastro'
      fullPath: '/auth/cadastro'
      preLoaderRoute: typeof AuthCadastroRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/completar-cadastro': {
      id: '/auth/completar-cadastro'
      path: '/completar-cadastro'
      fullPath: '/auth/completar-cadastro'
      preLoaderRoute: typeof AuthCompletarCadastroRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/perfil': {
      id: '/auth/perfil'
      path: '/perfil'
      fullPath: '/auth/perfil'
      preLoaderRoute: typeof AuthPerfilRouteImport
      parentRoute: typeof AuthRoute
    }
    '/motorista/mercadopago-callback': {
      id: '/motorista/mercadopago-callback'
      path: '/motorista/mercadopago-callback'
      fullPath: '/motorista/mercadopago-callback'
      preLoaderRoute: typeof MotoristaMercadopagoCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteChildren {
  AuthCadastroRoute: typeof AuthCadastroRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthCompletarCadastroRoute: typeof AuthCompletarCadastroRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthPerfilRoute: typeof AuthPerfilRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCadastroRoute: AuthCadastroRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthCompletarCadastroRoute: AuthCompletarCadastroRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthPerfilRoute: AuthPerfilRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcompanhamentoRoute: AcompanhamentoRoute,
  AuthRoute: AuthRouteWithChildren,
  ConfirmarCorridaRoute: ConfirmarCorridaRoute,
  CorridasRoute: CorridasRoute,
  HomeMotoristaRoute: HomeMotoristaRoute,
  MeusChamadosRoute: MeusChamadosRoute,
  OnboardingMotoristaRoute: OnboardingMotoristaRoute,
  PagamentoPixRoute: PagamentoPixRoute,
  PerfilRoute: PerfilRoute,
  PerfilMotoristaRoute: PerfilMotoristaRoute,
  ProcurandoMotoristaRoute: ProcurandoMotoristaRoute,
  ViagemCompartilhadaRoute: ViagemCompartilhadaRoute,
  AdminCidadesRoute: AdminCidadesRoute,
  AdminMotoristasRoute: AdminMotoristasRoute,
  AdminSuporteRoute: AdminSuporteRoute,
  AdminVeiculosRoute: AdminVeiculosRoute,
  MotoristaMercadopagoCallbackRoute: MotoristaMercadopagoCallbackRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
