/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcompanhamentoRouteImport } from './routes/acompanhamento'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ConfirmarCorridaRouteImport } from './routes/confirmar-corrida'
import { Route as CorridasRouteImport } from './routes/corridas'
import { Route as HomeMotoristaRouteImport } from './routes/home-motorista'
import { Route as OnboardingMotoristaRouteImport } from './routes/onboarding-motorista'
import { Route as ProcurandoMotoristaRouteImport } from './routes/procurando-motorista'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminCidadesRouteImport } from './routes/admin/cidades'
import { Route as AdminMotoristasRouteImport } from './routes/admin/motoristas'
import { Route as AdminVeiculosRouteImport } from './routes/admin/veiculos'
import { Route as AuthCadastroRouteImport } from './routes/auth.cadastro'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthCompletarCadastroRouteImport } from './routes/auth.completar-cadastro'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthPerfilRouteImport } from './routes/auth.perfil'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcompanhamentoRoute = AcompanhamentoRouteImport.update({
  id: '/acompanhamento',
  path: '/acompanhamento',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmarCorridaRoute = ConfirmarCorridaRouteImport.update({
  id: '/confirmar-corrida',
  path: '/confirmar-corrida',
  getParentRoute: () => rootRouteImport,
} as any)
const CorridasRoute = CorridasRouteImport.update({
  id: '/corridas',
  path: '/corridas',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeMotoristaRoute = HomeMotoristaRouteImport.update({
  id: '/home-motorista',
  path: '/home-motorista',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingMotoristaRoute = OnboardingMotoristaRouteImport.update({
  id: '/onboarding-motorista',
  path: '/onboarding-motorista',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcurandoMotoristaRoute = ProcurandoMotoristaRouteImport.update({
  id: '/procurando-motorista',
  path: '/procurando-motorista',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCidadesRoute = AdminCidadesRouteImport.update({
  id: '/admin/cidades',
  path: '/admin/cidades',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMotoristasRoute = AdminMotoristasRouteImport.update({
  id: '/admin/motoristas',
  path: '/admin/motoristas',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVeiculosRoute = AdminVeiculosRouteImport.update({
  id: '/admin/veiculos',
  path: '/admin/veiculos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCadastroRoute = AuthCadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCompletarCadastroRoute = AuthCompletarCadastroRouteImport.update({
  id: '/completar-cadastro',
  path: '/completar-cadastro',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPerfilRoute = AuthPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acompanhamento': typeof AcompanhamentoRoute
  '/auth': typeof AuthRouteWithChildren
  '/confirmar-corrida': typeof ConfirmarCorridaRoute
  '/corridas': typeof CorridasRoute
  '/home-motorista': typeof HomeMotoristaRoute
  '/onboarding-motorista': typeof OnboardingMotoristaRoute
  '/procurando-motorista': typeof ProcurandoMotoristaRoute
  '/admin/cidades': typeof AdminCidadesRoute
  '/admin/motoristas': typeof AdminMotoristasRoute
  '/admin/veiculos': typeof AdminVeiculosRoute
  '/auth/cadastro': typeof AuthCadastroRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/completar-cadastro': typeof AuthCompletarCadastroRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/perfil': typeof AuthPerfilRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acompanhamento': typeof AcompanhamentoRoute
  '/auth': typeof AuthRouteWithChildren
  '/confirmar-corrida': typeof ConfirmarCorridaRoute
  '/corridas': typeof CorridasRoute
  '/home-motorista': typeof HomeMotoristaRoute
  '/onboarding-motorista': typeof OnboardingMotoristaRoute
  '/procurando-motorista': typeof ProcurandoMotoristaRoute
  '/admin/cidades': typeof AdminCidadesRoute
  '/admin/motoristas': typeof AdminMotoristasRoute
  '/admin/veiculos': typeof AdminVeiculosRoute
  '/auth/cadastro': typeof AuthCadastroRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/completar-cadastro': typeof AuthCompletarCadastroRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/perfil': typeof AuthPerfilRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acompanhamento': typeof AcompanhamentoRoute
  '/auth': typeof AuthRouteWithChildren
  '/confirmar-corrida': typeof ConfirmarCorridaRoute
  '/corridas': typeof CorridasRoute
  '/home-motorista': typeof HomeMotoristaRoute
  '/onboarding-motorista': typeof OnboardingMotoristaRoute
  '/procurando-motorista': typeof ProcurandoMotoristaRoute
  '/admin/cidades': typeof AdminCidadesRoute
  '/admin/motoristas': typeof AdminMotoristasRoute
  '/admin/veiculos': typeof AdminVeiculosRoute
  '/auth/cadastro': typeof AuthCadastroRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/completar-cadastro': typeof AuthCompletarCadastroRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/perfil': typeof AuthPerfilRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acompanhamento'
    | '/auth'
    | '/confirmar-corrida'
    | '/corridas'
    | '/home-motorista'
    | '/onboarding-motorista'
    | '/procurando-motorista'
    | '/admin/cidades'
    | '/admin/motoristas'
    | '/admin/veiculos'
    | '/auth/cadastro'
    | '/auth/callback'
    | '/auth/completar-cadastro'
    | '/auth/login'
    | '/auth/perfil'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acompanhamento'
    | '/auth'
    | '/confirmar-corrida'
    | '/corridas'
    | '/home-motorista'
    | '/onboarding-motorista'
    | '/procurando-motorista'
    | '/admin/cidades'
    | '/admin/motoristas'
    | '/admin/veiculos'
    | '/auth/cadastro'
    | '/auth/callback'
    | '/auth/completar-cadastro'
    | '/auth/login'
    | '/auth/perfil'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/acompanhamento'
    | '/auth'
    | '/confirmar-corrida'
    | '/corridas'
    | '/home-motorista'
    | '/onboarding-motorista'
    | '/procurando-motorista'
    | '/admin/cidades'
    | '/admin/motoristas'
    | '/admin/veiculos'
    | '/auth/cadastro'
    | '/auth/callback'
    | '/auth/completar-cadastro'
    | '/auth/login'
    | '/auth/perfil'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcompanhamentoRoute: typeof AcompanhamentoRoute
  AuthRoute: typeof AuthRouteWithChildren
  ConfirmarCorridaRoute: typeof ConfirmarCorridaRoute
  CorridasRoute: typeof CorridasRoute
  HomeMotoristaRoute: typeof HomeMotoristaRoute
  OnboardingMotoristaRoute: typeof OnboardingMotoristaRoute
  ProcurandoMotoristaRoute: typeof ProcurandoMotoristaRoute
  AdminCidadesRoute: typeof AdminCidadesRoute
  AdminMotoristasRoute: typeof AdminMotoristasRoute
  AdminVeiculosRoute: typeof AdminVeiculosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acompanhamento': {
      id: '/acompanhamento'
      path: '/acompanhamento'
      fullPath: '/acompanhamento'
      preLoaderRoute: typeof AcompanhamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmar-corrida': {
      id: '/confirmar-corrida'
      path: '/confirmar-corrida'
      fullPath: '/confirmar-corrida'
      preLoaderRoute: typeof ConfirmarCorridaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corridas': {
      id: '/corridas'
      path: '/corridas'
      fullPath: '/corridas'
      preLoaderRoute: typeof CorridasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home-motorista': {
      id: '/home-motorista'
      path: '/home-motorista'
      fullPath: '/home-motorista'
      preLoaderRoute: typeof HomeMotoristaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding-motorista': {
      id: '/onboarding-motorista'
      path: '/onboarding-motorista'
      fullPath: '/onboarding-motorista'
      preLoaderRoute: typeof OnboardingMotoristaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procurando-motorista': {
      id: '/procurando-motorista'
      path: '/procurando-motorista'
      fullPath: '/procurando-motorista'
      preLoaderRoute: typeof ProcurandoMotoristaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/cidades': {
      id: '/admin/cidades'
      path: '/admin/cidades'
      fullPath: '/admin/cidades'
      preLoaderRoute: typeof AdminCidadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/motoristas': {
      id: '/admin/motoristas'
      path: '/admin/motoristas'
      fullPath: '/admin/motoristas'
      preLoaderRoute: typeof AdminMotoristasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/veiculos': {
      id: '/admin/veiculos'
      path: '/admin/veiculos'
      fullPath: '/admin/veiculos'
      preLoaderRoute: typeof AdminVeiculosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/cadastro': {
      id: '/auth/cadastro'
      path: '/cadastro'
      fullPath: '/auth/cadastro'
      preLoaderRoute: typeof AuthCadastroRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/completar-cadastro': {
      id: '/auth/completar-cadastro'
      path: '/completar-cadastro'
      fullPath: '/auth/completar-cadastro'
      preLoaderRoute: typeof AuthCompletarCadastroRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/perfil': {
      id: '/auth/perfil'
      path: '/perfil'
      fullPath: '/auth/perfil'
      preLoaderRoute: typeof AuthPerfilRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthCadastroRoute: typeof AuthCadastroRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthCompletarCadastroRoute: typeof AuthCompletarCadastroRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthPerfilRoute: typeof AuthPerfilRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCadastroRoute: AuthCadastroRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthCompletarCadastroRoute: AuthCompletarCadastroRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthPerfilRoute: AuthPerfilRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcompanhamentoRoute: AcompanhamentoRoute,
  AuthRoute: AuthRouteWithChildren,
  ConfirmarCorridaRoute: ConfirmarCorridaRoute,
  CorridasRoute: CorridasRoute,
  HomeMotoristaRoute: HomeMotoristaRoute,
  OnboardingMotoristaRoute: OnboardingMotoristaRoute,
  ProcurandoMotoristaRoute: ProcurandoMotoristaRoute,
  AdminCidadesRoute: AdminCidadesRoute,
  AdminMotoristasRoute: AdminMotoristasRoute,
  AdminVeiculosRoute: AdminVeiculosRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
