// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qycblinfvijhfjcmdoof.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF5Y2JsaW5mdmlqaGZqY21kb29mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODY5Nzg3NTcsImV4cCI6MjEwMjU1NDc1N30.DkeGXsmhGf1EJTFv4ll9haL3ViliCuSAydXTr8Akqus";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
    flowType: 'pkce',
  }
});